name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - v3
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: gh-pages
          folder: doc/html
          target_folder: v3
